export const navItems = [
  { label: "HOME", href: "#" },
  { label: "ABOUT US", href: "#" },
  { label: "EVENTS", href: "https://unstop.com/college-fests/e-summit25-netaji-subhas-university-of-technology-nsut-delhi-379875" },
  { label: "TEAM", href: "#" },
];


export const Ribbon = [
    {content: "I"},
    {content: "G"},
    {content: "N"},
    {content: "I"},
    {content: "T"},
    {content: "I"},
    {content: "N"},
    {content: "G"},
    {content: "  "},
    {content: "I"},
    {content: "N"},
    {content: "N"},
    {content: "O"},
    {content: "V"},
    {content: "A"},
    {content: "T"},
    {content: "I"},
    {content: "O"},
    {content: "N"},
    {content: "  "},
    {content: "E"},
    {content: "M"},
    {content: "P"},
    {content: "O"},
    {content: "W"},
    {content: "E"},
    {content: "R"},
    {content: "I"},
    {content: "N"},
    {content: "G"},
    {content: "  "},
    {content: "E"},
    {content: "N"},
    {content: "T"},
    {content: "R"},
    {content: "E"},
    {content: "P"},
    {content: "R"},
    {content: "E"},
    {content: "N"},
    {content: "E"},
    {content: "U"},
    {content: "R"},
    {content: "S"},
]

